# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:

      pypi_wayback:

        image: ghcr.io/waleko/pypi-wayback

        ports:

        - 8629:8080
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
          pytest \
          tox
        cp tests/config-ci.py config.py

    - name: Test on ${{ matrix.python-version }}
      run: |
        tox -e py

    - name: Check Distribution
      if: ${{ matrix.python-version == '3.9' }}
      run: |
        tox -e dist-check

    - name: Codestyle
      if: ${{ matrix.python-version == '3.9' }}
      run: |
        tox -e codestyle

    - name: Lint - sort
      if: ${{ matrix.python-version == '3.9' }}
      run: |
        tox -e sort

    - name: Security
      if: ${{ matrix.python-version == '3.9' }}
      run: |
        tox -e security

    - name: Docs
      if: ${{ matrix.python-version == '3.9' }}
      run: |
        tox -e docs

env:
  PIP_INDEX_URL: http://localhost:8629/2023-10-29
  UV_INDEX_URL: http://localhost:8629/2023-10-29
